### ISSUE TITLE
[BUG] comfyui address does not include port

### ISSUE THREAD

**Issue by thejohnd0e** [ModelSurge/sd-webui-comfyui#152]
I can't understand why the extension doesn't work, I only see a white screen.

[ComfyUI] [sd-webui-comfyui] Setting up IPC...
[ComfyUI] [sd-webui-comfyui] Using inter-process communication strategy: Shared memory
[ComfyUI] [sd-webui-comfyui] Started callback listeners for process comfyui
[ComfyUI] [sd-webui-comfyui] Patching ComfyUI...
Applying attention optimization: sdp... done.
Model loaded in 4.0s (load weights from disk: 0.6s, create model: 0.6s, apply weights to model: 1.0s, apply half(): 0.8s, move model to device: 0.9s).

![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/9b460c96-3e49-45c4-b19e-8cbc75827139)

**Comment by yujianvip** [comment]
I also made the same mistake, the correct calling address should be http://127.0.0.1:8188 But what Stable diffusion calls is http://127.0.0.1 , which has caused the inability to access, and I have not yet found a solution

**Comment by ljleb** [comment]
This does not look right. Did you set a custom address or this is by default? did you change any of the configuration?

**Comment by DennyCai** [comment]
```
Traceback (most recent call last):
  File "sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 7, in <module>
    from lib_comfyui import (
ModuleNotFoundError: No module named 'lib_comfyui'
```
Only see a white screen too.But I have an **Error**.

**Comment by ljleb** [comment]
@DennyCai this is caused by PYTHONPATH not setup properly, or something like that. I hope to fix this different issue in #155. For the missing port issue, I suspect this is because the comfyui client address is manually specified and does not include a port.

**Comment by klossm** [comment]
I had this problem with Chrome, I switched to Microsoft Edge and it worked fine, maybe it's not too compatible with Chrome!

**Comment by ljleb** [comment]
Sometimes the webui finishes loading before the comfyui server. That's what the reload comfyui interface button is for in the txt2img and img2img dropdown.

**Comment by ljleb** [comment]
I've made it so that the client url in the settings is canonicalized. Any missing info like port or protocol is added back, it should resolve the confusion created by the recent change of behavior.

**Comment by thejohnd0e** [comment]
It still doesn't work for me, and I don't know what I'm doing wrong.


<img width="969" alt="Screenshot - 2023-09-05 15 08 08" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/712fa47a-299f-4044-af4c-cd63d362e4df">

<img width="1537" alt="Screenshot - 2023-09-05 15 06 53" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/f118d823-ade1-4754-8e29-2746a3e5bdbf">

<img width="1294" alt="Screenshot - 2023-09-05 15 07 08" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/7f67b8da-f03e-4eb5-8da5-02eb8f5e8638">

**Comment by ljleb** [comment]
I'm missing context:
- how do you start the webui, is this on a remote server or locally?
- which version of the webui, the extension and comfyui are you running on, are all 3 on the latest version?
- which operating system are you running on?

From the short section of the logs you have provided, it looks like comfyui does not finish starting for some reason. Maybe the situation you are running into has to do with this.

**Comment by thejohnd0e** [comment]
I tried a new clean install but I got the same results 

<img width="962" alt="Screenshot - 2023-09-06 10 56 28" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/806e8e77-4bfc-48be-aca2-3be6fb5e7d4f">

<img width="1083" alt="Screenshot - 2023-09-06 10 53 38" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/b7725765-bd52-4421-a6a6-45f43ec22288">

<img width="583" alt="Screenshot - 2023-09-06 10 48 08" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/addd2963-162a-4034-832d-f960a85cacac">

<img width="190" alt="Screenshot - 2023-09-06 10 48 00" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/65a9881b-2950-4fee-9c89-ca18bd09856e">

<img width="468" alt="Screenshot - 2023-09-06 10 37 19" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/0bff8af6-b666-4365-803b-c74630d98b41">

**Comment by ljleb** [comment]
It looks like the comfyui subprocess is freezing during the patch phase on your setup. This is not caused by a port missing in the configuration.

Does it help in any way if you chose "File System" instead of "Default" for the interprocess communication strategy?

**Comment by thejohnd0e** [comment]
> It looks like the comfyui subprocess is freezing during the patch phase on your setup. This is not caused by a port missing in the configuration.
> 
> Does it help in any way if you chose "File System" instead of "Default" for the interprocess communication strategy?

I've done that, but the error is still there.

<img width="953" alt="Screenshot - 2023-09-07 07 32 13" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/47d71ee5-3e3b-4d46-9f7d-ccc3314f0f30">

<img width="232" alt="Screenshot - 2023-09-07 07 34 42" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/4c008b91-b72f-455d-a181-85a5e23f476f">

<img width="963" alt="Screenshot - 2023-09-07 07 37 57" src="https://github.com/ModelSurge/sd-webui-comfyui/assets/115493464/4502695b-8deb-4393-990c-dbf0b3439f83">
