### ISSUE TITLE
Unable to make it work (Google Colab)

### ISSUE THREAD

**Issue by gitzJess** [ModelSurge/sd-webui-comfyui#230]
I am trying to run it on Google Colab but it doesn't work at all, it returns a blank screen
Yes, I do have reverse proxy and --api.

**Comment by gitzJess** [comment]
![Blank](https://github.com/user-attachments/assets/afa825b8-8d03-4182-ba0b-214b74c7a74a)

**Comment by gitzJess** [comment]
Forgot to put the info lol

✔ Connected
[sd-webui-comfyui] Started callback listeners for process webui
[sd-webui-comfyui] Starting subprocess for comfyui...
[sd-webui-comfyui] Created a reverse proxy route to ComfyUI: /sd-webui-comfyui/comfyui
Startup time: 4.0s (list SD models: 0.8s, load scripts: 0.9s, create ui: 0.5s, gradio launch: 1.4s, add APIs: 0.2s).
[ComfyUI] [sd-webui-comfyui] Setting up IPC...
[ComfyUI] [sd-webui-comfyui] Using inter-process communication strategy: File system
[ComfyUI] [sd-webui-comfyui] Started callback listeners for process comfyui
[ComfyUI] [sd-webui-comfyui] Patching ComfyUI...
[ComfyUI] [sd-webui-comfyui] Launching ComfyUI with arguments: --listen 127.0.0.1 --port 8189
[ComfyUI] [START] Security scan
[ComfyUI] [DONE] Security scan
[ComfyUI] ## ComfyUI-Manager: installing dependencies done.
[ComfyUI] ** ComfyUI startup time: 2024-10-20 02:33:07.551448
[ComfyUI] ** Platform: Linux
[ComfyUI] ** Python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
[ComfyUI] ** Python executable: /usr/bin/python3
[ComfyUI] ** ComfyUI Path: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI
[ComfyUI] ** Log path: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/comfyui.log
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/pre_main.py", line 98, in <module>
    main()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/pre_main.py", line 44, in main
    start_comfyui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/pre_main.py", line 93, in start_comfyui
    runpy.run_path(os.path.join(os.getcwd(), 'main.py'), {'comfyui_print': comfyui_print}, '__main__')
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/main.py", line 66, in <module>
    import utils.extra_config
ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package

**Comment by PladsElsker** [comment]
Have you looked at #228? Some people say it worked over there. 

The repo is not actively maintained anymore, so this probably won't be fixed with a commit to main.

**Comment by gitzJess** [comment]
> Have you looked at #228? Some people say it worked over there.
> 
> The repo is not actively maintained anymore, so this probably won't be fixed with a commit to main.

Somehow I managed to fix it, but still can't use ComfyUI

I am getting this error now lol

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 70, in <module>
    import cchardet as chardet
ModuleNotFoundError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/pre_main.py", line 98, in <module>
    main()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/pre_main.py", line 43, in main
    patch_comfyui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc/__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/pre_main.py", line 86, in patch_comfyui
    routes_extension.patch_server_routes()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/routes_extension.py", line 8, in patch_server_routes
    add_server__init__patch(websocket_handler_patch)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/comfyui/routes_extension.py", line 13, in add_server__init__patch
    import server
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/server.py", line 21, in <module>
    import aiohttp
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 59, in <module>
    from .client_reqrep import (
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "/usr/local/lib/python3.10/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path
  File "/usr/local/lib/python3.10/dist-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/usr/local/lib/python3.10/dist-packages/charset_normalizer/cd.py", line 9, in <module>
    from .md import is_suspiciously_successive_range
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
caef7db17e06fcb1fc8dc98def13bafda3e8e1307d6d23fa83c46fbe18cf2b58
Loading weights [caef7db17e] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/[XL]YiffySeaArtFurry (0.6SeaX0.4Yiff).safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stablediffusion/generative-models/configs/inference/sd_xl_base.yaml
tokenizer_config.json100% 905/905 [00:00<00:00, 9.71MB/s]
vocab.json100% 961k/961k [00:00<00:00, 2.89MB/s]
merges.txt100% 525k/525k [00:00<00:00, 2.11MB/s]
special_tokens_map.json100% 389/389 [00:00<00:00, 4.26MB/s]
tokenizer.json100% 2.22M/2.22M [00:00<00:00, 5.30MB/s]
creating model quickly: OSError
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1484, in _raise_on_head_call_error
    raise head_call_error
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 301, in _request_wrapper
    hf_raise_for_status(response)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_http.py", line 454, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-67148057-6adf7a546d9dcfcd52fbad30;f87ebff1-8590-4ab6-ba0f-75dee8263487)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 149, in load_model
    shared.sd_model  # noqa: B018
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared_items.py", line 175, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 693, in get_sd_model
    load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 820, in load_model
    sd_model = instantiate_from_config(sd_config.model, state_dict)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 775, in instantiate_from_config
    return constructor(**params)
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/models/diffusion.py", line 61, in __init__
    self.conditioner = instantiate_from_config(
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/modules/encoders/modules.py", line 88, in __init__
    embedder = instantiate_from_config(embconfig)
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/modules/encoders/modules.py", line 361, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_disable_initialization.py", line 68, in CLIPTextModel_from_pretrained
    res = self.CLIPTextModel_from_pretrained(None, *model_args, config=pretrained_model_name_or_path, state_dict={}, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3301, in from_pretrained
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 426, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
