### ISSUE TITLE
ConfyUI using domain

### ISSUE THREAD

**Issue by Harao90** [ModelSurge/sd-webui-comfyui#82]
I have my Stable Diffusion "public" and was trying to have ConfyUI on it, but I can't configure the page the tab is trying to go, so it goes to the local host. is there any way I can redirect it to my domain or do I have to do a workaround?

In the machine where I am running Stable Diffusion it all works as intended.

![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/72939996/be4f5ae8-2eee-4188-b0af-b93763064f18)

**Comment by ljleb** [comment]
Are you trying to run both the webui and comfyui on the same machine, or you are trying to start comfyui on a different machine from comfyui?

At the moment, it is not possible to separate them. We are considering making this possible, although it is not a priority ATM.

If you simply need the webui to try to connect to a different url for some reason, then you can change the "Address of the ComfyUI server as seen from the webui" in the settings of the extension.

**Comment by ljleb** [comment]
Note that you have to wait for the comfyui server to finish loading ATM for it to work. Keep an eye on #77 the resolution of this issue.

**Comment by ljleb** [comment]
I see. Can you share your logs? Is there a message that looks like "[ComfyUI extension] changing the ComfyUI client address from {client_url} to {loopback_address}"?

**Comment by Harao90** [comment]
> 

Found this

![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/72939996/0cdb7474-a077-47df-8b70-25c2aeb2c7d4)

i am trying to use --webui-comfyui-client-address <address>, adding --client-address confy.domain.com to the Additional cli arguments on stable diffusion webui, but it says the argument is not right, but i think it is on the right path.

**Comment by ljleb** [comment]
The argument has to be `--webui-comfyui-client-address confy.domain.com`, not just "--client-address". However it's odd that the settings are ignored. Are you sure they have been saved? The settings should take priority over the cli arguments.

**Comment by Harao90** [comment]
> 

got some progress

![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/72939996/df6da187-a0b8-4d4b-b2c2-576399de6887)

Not working yet, but it is starting to appear something is changing, i tried with the domain and it puts the http and port automatically so i thought it was because of that. Change it to just the ip, and the same result, all white.

ill try some more things and give feedback.

if you think of something please say, for now ill continue using it as i had before and tackle this later, it was just to have everything in one place. 

Thanks for the help!

**Comment by ljleb** [comment]
Wait, which webui host is this? It does not look like a1111 or vlad. We can't support all possible webui hosts implementation, it just wouldn't be practical to aim for this... Does the extension work for your use case in a1111 or vlad?

**Comment by ljleb** [comment]
Do I understand that issue is resolved then? Or your earlier setup is also a local installation that did not work for some reason

**Comment by Harao90** [comment]
> Do I understand that the issue is resolved then? Or your earlier setup is also a local installation that did not work for some reason

It is not resolved, I put everything to default and used the local machine to show it works as intended.

When I access from my domain, everything is default, it can't connect to confyUI because it tries to access 127.0.0.1 and fails, as it should. When I use the `--webui-comfyui-client-address confy.domain.com` or  `--webui-comfyui-client-address 192.168.x.x` it gives no error just white.

When I have time ill try a new a1111 installation just with the extension to try to isolate the issue.

**Comment by ljleb** [comment]
Ah wait, now I understand your setup. I don't have a domain name to test with, so it's hard for me to debug this. I'm not sure why the ui is all white like that. In the end, the comfyui tab we added is really just an iframe trying to load the content from a specified address. The tab shouldn't do anything special on the ui side.

Maybe it's stuck for some reason during loading? I'm not quite sure. Could you share the entire logs? It may show whether comfyui is starting or not. Maybe I could spot a clue in there.

**Comment by E2GO** [comment]
Same issue.

**Comment by ljleb** [comment]
For reverse proxy users, the problem is that reverse proxy needs to be implemented for comfyui in addition to the existing reverse proxy for the webui.

We were considering adding a local tunnel implementation but it turned out to be a lot of work. we may add it some time in the future. PRs are welcome for this use case. We are focusing on more urgent matters, but may come back to this at some point.

**Comment by ljleb** [comment]
related: #9

**Comment by ljleb** [comment]
#91 should have fixed the url setting not being taken into account. @Harao90 let us know if the issue is fixed on your end with this option.

**Comment by ljleb** [comment]
A solution for reverse proxy to work without setting up separate proxies for the webui and comfyui would be to setup a specific route in a1111, for example http://localhost:7860/sd-webui-comfyui/comfyui, as a reverse proxy to http://localhost:8189 (actual comfyui server)

**Comment by rookiexjl** [comment]
--comfyui-listen --webui-comfyui-client-address 192.168.xx,xx   add is ok

**Comment by vivagonna** [comment]
> --comfyui-listen --webui-comfyui-client-address 192.168.xx,xx add is ok

Seems not work

**Comment by rookiexjl** [comment]
&nbsp;--xformers --autolaunch --theme dark --api --listen&nbsp; --comfyui-listen --webui-comfyui-client-address 192.168.xx.xx&nbsp;
all,your check,try




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月15日(星期二) 凌晨5:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ModelSurge/sd-webui-comfyui] ConfyUI using domain (Issue #82)





  
--comfyui-listen --webui-comfyui-client-address 192.168.xx,xx add is ok
  
Seems not work

**Comment by rookiexjl** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ModelSurge/sd-webui-comfyui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月15日(星期二) 凌晨5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ModelSurge/sd-webui-comfyui] ConfyUI using domain (Issue #82)





  
--comfyui-listen --webui-comfyui-client-address 192.168.xx,xx add is ok
  
Seems not work

**Comment by ljleb** [comment]
The extension should work for reverse proxy users now.

**Comment by rookiexjl** [comment]
![1692237976438](https://github.com/ModelSurge/sd-webui-comfyui/assets/19485623/d0006619-8239-4716-816a-3d72514b1e2c)
![1692063463456](https://github.com/ModelSurge/sd-webui-comfyui/assets/19485623/0c158511-943c-40e0-9831-b48966dd54f4)
![1692237858214](https://github.com/ModelSurge/sd-webui-comfyui/assets/19485623/aa238a4d-f1d5-420d-a07f-b3bfdb0fd638)

**Comment by ljleb** [comment]
Is there a line `[sd-webui-comfyui] Created a reverse proxy route to ComfyUI: /sd-webui-comfyui/comfyui` in the logs? If not, your setup does not seem to require a reverse proxy to work. This is different from other people using runpod.io for example.

**Comment by rookiexjl** [comment]
[ComfyUI] Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : native
[ComfyUI] Using xformers cross attention
[ComfyUI] [sd-webui-comfyui] Launching ComfyUI with arguments: --listen 0.0.0.0 --port 8189
[ComfyUI]
Other computers can use ComfyUI 192.168.xx.xx:7860
